apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 1m0s
  ref:
    branch: Main
  url: https://github.com/sammyrules7/fluxcd-test
