apiVersion: v1
kind: Pod
metadata:
  name: fabric
  namespace: minecraft
spec:
  containers:
    - name: fabric
      image: itzg/minecraft-server
      ports:
        - containerPort: 25565
      env:
        - name: EULA
          value: "true"
        - name: MODRINTH_MODPACK
          value: "BYN9yKrV"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: minecraft
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
